version: 4.5.30-{build}

branches:
  only:
    - master
    - /v\d+\.\d+\.\d+/

image: Visual Studio 2022

clone_depth: 1
clone_folder: C:\build

environment:
  SELF_SIGNED_CERTIFICATE_PASSWORD:
    secure: Gq8/2YxZYUsUkyG9wl5L02sJG6Vuvf3GJEXulu7oSci4RJvoT0CMze9PgaTYU9Xh

build_script:
  - cmd: cd Build && Build.bat

artifacts:
  - path: Build/Rainmeter-*.exe

deploy:
- provider: Webhook
  url: https://app.signpath.io/API/v1/2d37d539-98b7-4649-9469-4097b1099202/Integrations/AppVeyor?ProjectSlug=rainmeter&SigningPolicySlug=release-signing
  authorization:
    secure: YnZH/YJ9Me+6CY6WhyO44nJjzjquWn7IGGxaj3xDT/JOUVMMB5IBf2GVQwutF/l26WstrHNmaFZCGTMvXuc4Cg==
  on:
    APPVEYOR_REPO_TAG: true
